name: Ejecucion Automatizada de Ingesta

on:
  push:
    branches: [ main ]  # Se ejecuta cada vez que subes cambios a la rama main
  workflow_dispatch:     # Permite ejecutarlo manualmente desde la pestaña "Actions"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          pip install requests pandas openpyxl

      - name: Ejecutar script de ingesta
        run: python src/ingestion.py

      - name: Guardar cambios en el repositorio
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add src/db/ingestion.db src/xlsx/ingestion.xlsx src/static/auditoria/ingestion.txt
          git commit -m "Actualización automática de datos y evidencias" || echo "Sin cambios para commitear"
          git push