name: Pipeline Big Data (EA1 + EA2 + EA3)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      # 1. Preparación del Entorno
      - name: Checkout del codigo
        uses: actions/checkout@v3

      - name: Configurar Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas openpyxl

      # 2. Ejecución de las 3 Fases del Proyecto Integrador
      - name: Fase 1: Ingesta de datos (EA1)
        run: python src/ingestion.py

      - name: Fase 2: Limpieza de datos (EA2)
        run: python src/cleaning.py

      - name: Fase 3: Enriquecimiento de datos (EA3)
        run: python src/enrichement.py

      # 3. Guardado Automático para videncias en el Repositorio
      - name: Commit y Push de resultados finales
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "EA3: Pipeline completado - Enriquecimiento y reportes generados" || echo "Sin cambios para commitear"
          git push